# Generated by Django 4.2.1 on 2023-08-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('switch_name', models.CharField(max_length=100)),
                ('switch_status', models.BooleanField(default=False)),
            ],
        ),
    ]
